// @generated by Clarity — flat-file data module (@clarity-flat-db v1)
// PLATFORM-OWNED DATA MODULE. Do not edit or recreate this file. Put app data
// in database/seed.json (hand-editable) and app logic in your own hooks (e.g.
// src/hooks/useAppData.ts) via useTable/db. A separate program later swaps this
// implementation for SQL/Postgres/DocDB behind the same interface.
import { useMemo, useSyncExternalStore } from 'react'
import seedData from '../../database/seed.json'

type Row = Record<string, any>
const seed = (seedData || {}) as Record<string, Row[]>
const PROJECT =
  (typeof window !== 'undefined' && (window as any).__CLARITY_PROJECT_ID__) || 'preview'
let HASH = '0'
try {
  const s = JSON.stringify(seed)
  let h = 5381
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0
  HASH = (h >>> 0).toString(36)
} catch { HASH = '0' }
const LS_KEY = 'clarity-preview-db:v1:' + PROJECT + ':' + HASH

let version = 0
const listeners = new Set<() => void>()
let store: Record<string, Row[]> = loadTables()

function loadTables(): Record<string, Row[]> {
  try {
    const raw = localStorage.getItem(LS_KEY)
    if (raw) return JSON.parse(raw)
  } catch (err) { /* fall back to seed */ }
  const out: Record<string, Row[]> = {}
  for (const key of Object.keys(seed)) {
    if (Array.isArray(seed[key])) out[key] = seed[key].map((r) => ({ ...r }))
  }
  return out
}
function commit() {
  version += 1
  try { localStorage.setItem(LS_KEY, JSON.stringify(store)) } catch (err) { /* ignore */ }
  listeners.forEach((l) => l())
}
function subscribe(l: () => void) {
  listeners.add(l)
  return () => { listeners.delete(l) }
}
function rowsOf(name: string): Row[] {
  if (!store[name]) store[name] = []
  return store[name]
}
function nextId(name: string): string {
  let max = 0
  for (const r of rowsOf(name)) {
    const n = Number(r.id)
    if (Number.isFinite(n) && n > max) max = n
  }
  return String(max + 1)
}

export interface Table<T extends Row = Row> {
  list(where?: (row: T) => boolean): T[]
  get(id: string | number): T | undefined
  create(values: Partial<T>): T
  update(id: string | number, patch: Partial<T>): T | undefined
  remove(id: string | number): void
}

function makeTable<T extends Row = Row>(name: string): Table<T> {
  return {
    list: (where) => {
      const all = rowsOf(name) as T[]
      return where ? all.filter(where) : all.slice()
    },
    get: (id) => (rowsOf(name) as T[]).find((r) => String(r.id) === String(id)),
    create: (values) => {
      const row = { id: nextId(name), ...values } as T
      rowsOf(name).push(row)
      commit()
      return row
    },
    update: (id, patch) => {
      const row = (rowsOf(name) as T[]).find((r) => String(r.id) === String(id))
      if (row) { Object.assign(row, patch); commit() }
      return row
    },
    remove: (id) => {
      store[name] = rowsOf(name).filter((r) => String(r.id) !== String(id))
      commit()
    },
  }
}

export const db = { table: makeTable }

export function useTable<T extends Row = Row>(name: string): Table<T> {
  useSyncExternalStore(subscribe, () => version, () => version)
  return makeTable<T>(name)
}

// --- Minimal SQL compat, for platform-generated managed auth ONLY. ---
// App data must use useTable/db. This understands only the fixed single-table
// shapes auth uses and throws on anything more complex.
function coerce(token: string, params: any[], counter: { i: number }): any {
  const t = token.trim()
  if (t === '?') return params[counter.i++]
  if (t.length >= 2 && t[0] === "'" && t[t.length - 1] === "'") {
    return t.slice(1, -1).split("''").join("'")
  }
  if (t.toLowerCase() === 'null') return null
  if (t.toLowerCase() === 'true') return true
  if (t.toLowerCase() === 'false') return false
  const n = Number(t)
  return Number.isFinite(n) ? n : t
}
function parseEquals(clause: string, params: any[], counter: { i: number }) {
  return clause.split(/ and /i).map((cond) => {
    const eq = cond.indexOf('=')
    if (eq === -1) throw new Error('data module: unsupported condition ' + cond)
    return { col: cond.slice(0, eq).trim(), val: coerce(cond.slice(eq + 1), params, counter) }
  })
}
function runSql(sql: string, params: any[] = []): { rows: Row[]; rowCount: number } {
  let text = String(sql || '').trim()
  while (text.endsWith(';')) text = text.slice(0, -1).trim()
  const lower = text.toLowerCase()
  const counter = { i: 0 }

  if (lower.startsWith('select')) {
    const fromIdx = lower.indexOf(' from ')
    if (fromIdx === -1) throw new Error('data module: unsupported SELECT')
    const afterFrom = text.slice(fromIdx + 6).trim()
    const whereIdx = afterFrom.toLowerCase().indexOf(' where ')
    const table = (whereIdx === -1 ? afterFrom : afterFrom.slice(0, whereIdx)).trim().toLowerCase()
    const t = makeTable(table)
    if (whereIdx === -1) { const rows = t.list(); return { rows, rowCount: rows.length } }
    const conds = parseEquals(afterFrom.slice(whereIdx + 7), params, counter)
    const rows = t.list((r: any) => conds.every((c) => String(r[c.col]) === String(c.val)))
    return { rows, rowCount: rows.length }
  }
  if (lower.startsWith('insert into')) {
    const open = text.indexOf('(')
    const close = text.indexOf(')')
    const table = text.slice(11, open).trim().toLowerCase()
    const cols = text.slice(open + 1, close).split(',').map((c) => c.trim())
    const vOpen = text.indexOf('(', close)
    const vClose = text.indexOf(')', vOpen)
    const vals = text.slice(vOpen + 1, vClose).split(',')
    const row: Row = {}
    cols.forEach((c, idx) => { row[c] = coerce(vals[idx], params, counter) })
    return { rows: [makeTable(table).create(row)], rowCount: 1 }
  }
  if (lower.startsWith('update')) {
    const setIdx = lower.indexOf(' set ')
    const whereIdx = lower.indexOf(' where ')
    const table = text.slice(6, setIdx).trim().toLowerCase()
    const t = makeTable(table)
    const patch: Row = {}
    for (const a of text.slice(setIdx + 5, whereIdx).split(',')) {
      const eq = a.indexOf('=')
      patch[a.slice(0, eq).trim()] = coerce(a.slice(eq + 1), params, counter)
    }
    const conds = parseEquals(text.slice(whereIdx + 7), params, counter)
    const targets = t.list((r: any) => conds.every((c) => String(r[c.col]) === String(c.val)))
    targets.forEach((r: any) => t.update(r.id, patch))
    return { rows: targets, rowCount: targets.length }
  }
  if (lower.startsWith('delete')) {
    const whereIdx = lower.indexOf(' where ')
    const fromIdx = lower.indexOf(' from ')
    const table = text.slice(fromIdx + 6, whereIdx).trim().toLowerCase()
    const t = makeTable(table)
    const conds = parseEquals(text.slice(whereIdx + 7), params, counter)
    const targets = t.list((r: any) => conds.every((c) => String(r[c.col]) === String(c.val)))
    targets.forEach((r: any) => t.remove(r.id))
    return { rows: [], rowCount: targets.length }
  }
  throw new Error('Preview data module: use useTable/db for app data. Unsupported SQL: ' + text.slice(0, 60))
}

export async function query<T = Row>(sql: string, params: any[] = []): Promise<T[]> {
  return runSql(sql, params).rows as T[]
}
export async function exec(sql: string, params: any[] = []): Promise<{ rowCount: number }> {
  return { rowCount: runSql(sql, params).rowCount }
}
export function useQuery<T = Row>(sql: string, params: any[] = []) {
  useSyncExternalStore(subscribe, () => version, () => version)
  const key = JSON.stringify(params)
  const data = useMemo(() => {
    try { return runSql(sql, params).rows as T[] } catch (err) { return [] as T[] }
  }, [sql, key, version])
  return { data, loading: false, error: null as unknown, refetch: () => {} }
}
export function useMutation() {
  return {
    mutate: (sql: string, params: any[] = []) => runSql(sql, params),
    mutateAsync: async (sql: string, params: any[] = []) => runSql(sql, params),
    loading: false,
    error: null as unknown,
  }
}
